theme: jekyll-theme-slate
title: 1st Workshop on Conceptual Modeling Meets Artificial Intelligence and Data-Driven Decision Making (CMAI 2020)
description: Co-Located with the 39th International Conference on Conceptual Modeling (ER 2020), November 3-6, 2020, Vienna, Austria
plugins:
  - jekyll-relative-links
  - jekyll-redirect-from
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
